// packages/vue/src/components/button/Button.vue
<script setup lang="ts">
import * as styles from "@patrick-ui/core/button/button.css";
import { computed, defineProps } from 'vue';

interface ButtonProps {
    primary?: boolean
}

const props = defineProps<ButtonProps>()
const className = computed(() => styles.button({ primary: props.primary }))
</script>

<template>
    <button :class="className">
        <slot></slot>
    </button>
</template>

// packages/react/src/button/button.tsx
import * as styles from "@patrick-ui/core/button/button.css";
import React from "react";

export interface ButtonProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: "primary" | "secondary";
}

export const Button: React.FC<ButtonProps> = ({
  children,
  variant = "primary",
  ...props
}) => {
  return (
    <button className={styles.button({ primary: true })} {...props}>
      {children}
    </button>
  );
};

Button.displayName = "PatrickUIButton";
